class Promotion::PromotionRule < ActiveRecord::Base
  # table name
  self.table_name = 'promotion_rules'
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  belongs_to :promotion
  # validations ...............................................................
  validates :type_name, presence: true
  # validates :preferences, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  def is_user_usge(user,order)
    if self.type_name == "only_one"
      user.orders.exists?(promotion_id: self.promotion.id) ? false : self.promotion.promotion_actions.first.promotion_amount(order)
    else self.type_name == "every_order"
      order.promotion.blank? ? self.promotion.promotion_actions.first.promotion_amount(order) : false
    end
  end
  # private instance methods ..................................................
end
