class Promotion::PromotionAction < ActiveRecord::Base
  # table name
  self.table_name = 'promotion_actions'
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  belongs_to :promotion
  # validations ...............................................................
  validates :type_name, presence: true
  validates :preferences, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  def promotion_amount(order)
    order.total >= self.preferences.match(/min:(\d+)/)[1].to_f ? self.preferences.match(/amount:(\d+)/)[1].to_f : false
  end
  # private instance methods ..................................................
end
