class Order::Cart < ActiveRecord::Base
  # table name
  self.table_name = 'carts'
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  belongs_to :user
  has_many :line_items, dependent: :destroy, inverse_of: :cart
  has_many :variants, through: :line_items
  has_many :products, through: :variants
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  accepts_nested_attributes_for :line_items
  # class methods .............................................................
  # public instance methods ...................................................
  def add_line_item(variant_id)
    current_item = line_items.find_or_initialize_by(variant_id: variant_id)
    current_item.quantity += 1 if current_item.persisted?
    current_item
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
