class User::EmailVerificationCode < User::VerificationCode
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  # validations ...............................................................
  validates :to, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  # callbacks .................................................................
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  private

  def generate_code
    self.code = SecureRandom.hex
  end

  def send_notification
    url = Rails.application.routes.url_helpers.new_activation_url(code: code, host: 'http://fandore.net')
    pusher = Submail.pusher(Figaro.env.mail_app_id, Figaro.env.mail_signature)
    pusher.mail_xsend(to, '99cVp3', { url: url }, { url: url })
  end
end
