class User::MobileVerificationCode < User::VerificationCode
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  # validations ...............................................................
  validates :to, format: { with: /\A(13[0-9]|15[0-9]|18[7-8])[0-9]{8}\z/ }
  # callbacks .................................................................
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  private

  def generate_code
    self.code = SecureRandom.random_number.to_s[2, 6]
  end

  def project_code
    case method.to_sym
    when :send_verification
      Figaro.env.message_project_verification
    end
  end

  def send_notification
    pusher = Submail.pusher(Figaro.env.message_app_id, Figaro.env.message_signature)
    pusher.message_xsend(to, project_code, { sms_reg_code: code })
  end
end
