class User::Profile < ActiveRecord::Base
  # table name
  self.table_name = 'profiles'
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  belongs_to :user
  # validations ...............................................................
  validates :question, presence: true, length: { minimum: 6 }, allow_blank: true
  validates :answer,
            presence: true,
            length: { minimum: 2 },
            if: Proc.new { |profile| profile.question.present? }
  # callbacks .................................................................
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  enum gender: [ :female, :male ]
  mount_uploader :avatar, AvatarUploader
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................

  def i18n_gender
    I18n.t :"enumerize.user/profile.gender.#{gender}"
  end
end
