class User::Profile < ActiveRecord::Base
  # table name
  self.table_name = 'profiles'
  # extends ...................................................................
  extend Enumerize
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  belongs_to :user
  # validations ...............................................................
  validates :question, presence: true, length: { minimum: 6 }, allow_blank: true
  validates :answer,
            presence: true,
            length: { minimum: 2 },
            if: Proc.new { |profile| profile.question.present? }
  # callbacks .................................................................
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  enumerize :gender, in: { male: 1, female: 0 }
  mount_uploader :avatar, AvatarUploader
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
