class User::VerificationCode < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  self.table_name = "verification_codes"
  # related macros ............................................................
  # relationships .............................................................
  belongs_to :user
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  # class methods .............................................................
  class << self
    def send_verification_code(mobile)
      user = User.find_by(mobile: mobile.to_s)
      code = user.otp_code(time: Time.now + 1200)
      User::VerificationCode.create(user: user, code: code, mobile: user.mobile)
      # User::Sms.send_message(mobile,'twMG94',"sms_reg_code : #{code}")
    end

    def registration_code(mobile)
      code = rand(999999)
      User::VerificationCode.create(code: code, mobile: mobile)
      # User::Sms.send_message(mobile,'twMG94',"sms_reg_code : #{code}")
    end


    def self.verify(mobile, code)
      user = User.find_by(mobile: mobile)
      user && user.authenticate_otp(code, drift: 1200)
    end
  end
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  private

  def generate_code
    Time.now.to_i[0..5]
  end
end
