class Product::ProductProperty < ActiveRecord::Base
  # table name
  self.table_name = 'product_properties'
  # extends ...................................................................
  acts_as_list scope: :product
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  belongs_to :product, touch: true, inverse_of: :product_properties
  belongs_to :property, inverse_of: :product_properties
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
