class Product::Property < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  self.table_name = 'properties'
  # related macros ............................................................
  # relationships .............................................................
  # has_many :product_properties, dependent: :delete_all, inverse_of: :property
  # has_many :products, through: :product_properties
  #
  # has_and_belongs_to_many :prototypes
  # validations ...............................................................
  validates :name, :presentation, presence: true
  # callbacks .................................................................
  after_touch :touch_all_products
  # scopes ....................................................................
  scope :sorted, -> { order(:name) }
  # other macros (like devise's) ..............................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  private
    def touch_all_products
      products.each(&:touch)
    end
end
