class Product::Variant < ActiveRecord::Base
  # table name
  self.table_name = 'variants'
  # extends ...................................................................
  acts_as_paranoid
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  belongs_to :product, touch: true, inverse_of: :variants
  # belongs_to :tax_category

  has_many :option_value_variants
  has_many :option_values, through: :option_value_variants

  # has_many :prices, dependent: :destroy, inverse_of: :variant
  # relationships .............................................................
  # validations ...............................................................
  validates_uniqueness_of :sku, conditions: -> { where(deleted_at: nil) }
  # callbacks .................................................................
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
