class Payment::Wxpay < Payment::PaymentMethod
  # table name
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  # class methods .............................................................
  # public instance methods ...................................................
  def pay_url(order, client_ip="0.0.0.0")
    pingxx_result = Pingpp::Charge.create(
      :subject  => order.order_name,
      :body     => order.products.map(&:name).join(","),
      :amount   => order.total * 100,
      # :amount   => 1,
      :order_no => order.number,
      :channel  => "wx_pub_qr",
      :currency => "cny",
      :client_ip=> client_ip,
      :extra=> {'product_id' => order.products.first.id},
      :app => {'id' => "app_WHSmb5CuLCK0uf9u"}
    )
    pingxx_info = order.build_pingxx_info(pingxx_id: pingxx_result[:id], 
                                              channel: pingxx_result[:channel],
                                              amount: pingxx_result[:amount],
                                              time_expire: pingxx_result[:time_expire])
    if pingxx_info.save
      wx_pub_qr = pingxx_result[:credential][:wx_pub_qr]
      qr_path = "public/uploads/wx_pub_qr/#{order.number}.png"
      RQRCode::QRCode.new( wx_pub_qr, :size => 5, :level => :h ).to_img.resize(200, 200).save(qr_path)
      Rails.application.routes.url_helpers.wx_qr_payment_order_path(order)
    end
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
