class Comment < ActiveRecord::Base
  # table name
  # extends ...................................................................
  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable
  # includes ..................................................................
  include ActsAsCommentable::Comment
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  belongs_to :commentable, :polymorphic => true
  belongs_to :user
  # validations ...............................................................
  validates_uniqueness_of :commentable_id, scope: [:user_id, :commentable_type]
  # callbacks .................................................................
  # scopes ....................................................................
  default_scope -> { order('created_at ASC') }
  # other macros (like devise's) ..............................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
