class Favorite < ActiveRecord::Base
  # table name
  # extends ...................................................................
  # includes ..................................................................
  include ActsAsFavable::Favorite
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  belongs_to :favable, :polymorphic => true
  belongs_to :user
  # validations ...............................................................
  validates_uniqueness_of :favable_id, scope: [:user_id, :favable_type]
  # callbacks .................................................................
  # scopes ....................................................................
  default_scope { order('created_at ASC') }
  # other macros (like devise's) ..............................................
  # class methods .............................................................
  def self.is_favorite?(obj)
    !find_favorites_for_favable(obj.class.name, obj.id).size.zero?
  end
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
