class Promotion < ActiveRecord::Base
  # table name
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  belongs_to :promotion_category

  has_many :promotion_actions, dependent: :destroy
  alias_method :actions, :promotion_actions

  has_many :promotion_rules, dependent: :destroy
  alias_method :rules, :promotion_rules
  # validations ...............................................................
  validates :expires_at, presence: true
  validates :starts_at, presence: true
  validates :name, presence: true
  validates :usage_limit, presence: true
  validates :code, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
