class Taxonomy < ActiveRecord::Base
  # table name
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  has_many :taxons, inverse_of: :taxonomy
  has_one :root, -> { roots }, class_name: "Taxonomy::Taxon", dependent: :destroy
  # validations ...............................................................
  validates :name, presence: true
  # callbacks .................................................................
  after_create :set_root
  after_save :set_root_taxon_name
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  private

  def set_root
    self.root ||= taxons.create!(name: name)
  end

  def set_root_taxon_name
    taxons.root.update_attributes(name: name)
  end
end
