class User < ActiveRecord::Base
  # extends ...................................................................
  extend Enumerize

  has_secure_password
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  # validations ...............................................................
  validates :mobile, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :email,
            presence: true,
            length: { in: 6..20 },
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  # callbacks .................................................................
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  enumerize :gender, in: {male: 1, female: 0}
  mount_uploader :avatar, AvatarUploader

  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
