class Taxonomy::Classification < ActiveRecord::Base
  # table name
  self.table_name = 'products_taxons'
  # extends ...................................................................
  acts_as_list scope: :taxon
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  belongs_to :product, inverse_of: :classifications
  belongs_to :taxon, inverse_of: :classifications, touch: true
  # validations ...............................................................
  validates_uniqueness_of :taxon_id, scope: :product_id, message: :already_linked
  # callbacks .................................................................
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
