class Taxonomy::Taxon < ActiveRecord::Base
  # table name
  self.table_name = 'taxons'
  # extends ...................................................................
  has_ancestry
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  belongs_to :taxonomy, inverse_of: :taxons
  has_many :classifications, -> { order(:position) }, dependent: :delete_all, inverse_of: :taxon
  has_many :products, through: :classifications
  # validations ...............................................................
  validates :name, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  scope :goods, -> { where.not(name: '钻石')}
  scope :diamond, -> { where(name: '钻石')}
  scope :by_name, ->(name) { where(name: name)}
  # other macros (like devise's) ..............................................
  NAMES = { wedding: '结婚对戒', engaement: '求婚钻戒' }
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
